services:
    cms-db:
        image: mysql:8.0
        volumes:
            - "xibo-db:/var/lib/mysql"
            - "xibo-backup:/var/lib/backup"
        environment:
            - MYSQL_DATABASE=cms
            - MYSQL_USER=cms
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        restart: always
        command:
            --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
            --default-authentication-plugin=mysql_native_password

    cms-xmr:
        build:
            context: https://github.com/euaugusto1/xibo-xmr.git#develop
        ports:
            - "9505:9505"
        restart: always
        environment:
            - XMR_DEBUG=false

    cms-web:
        build:
            context: https://github.com/euaugusto1/xibo-cms.git#develop
        volumes:
            - "xibo-custom:/var/www/cms/custom"
            - "xibo-backup:/var/www/backup"
            - "xibo-theme:/var/www/cms/web/theme/custom"
            - "xibo-library:/var/www/cms/library"
            - "xibo-userscripts:/var/www/cms/web/userscripts"
            - "xibo-cacerts:/var/www/cms/ca-certs"
        restart: always
        depends_on:
            - cms-db
            - cms-xmr
        environment:
            - SERVICE_FQDN_CMS_80
            - MYSQL_HOST=cms-db
            - MYSQL_USER=cms
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=cms
            - XMR_HOST=cms-xmr
            - CMS_USE_MEMCACHED=true
            - MEMCACHED_HOST=cms-memcached
            - CMS_QUICK_CHART_URL=http://cms-quickchart:3400
            - CMS_SERVER_NAME=${SERVICE_FQDN_CMS}
        expose:
            - "80"

    cms-memcached:
        image: memcached:alpine
        command: memcached -m 15
        restart: always

    cms-quickchart:
        image: ianw/quickchart
        restart: always

volumes:
    xibo-db:
    xibo-backup:
    xibo-custom:
    xibo-theme:
    xibo-library:
    xibo-userscripts:
    xibo-cacerts: